return {}
-- return
--   {
--     "neovim/nvim-lspconfig",
--     opts = {
--       servers = {
--         tailwindcss = {
--           -- this is same as includeLanguages in vscode plugin?
--           init_options = {
--             userLanguages = {
--               gotmpl = "html",
--             },
--           },
--         },
--       },
--     },
--   },
--   {
--     "NvChad/nvim-colorizer.lua",
--     opts = {
--       user_default_options = {
--         tailwind = true,
--       },
--     },
--   },
-- }
