# This is the 1Password SSH agent config file
# Enable SSH keys from the Personal vault

[[ssh-keys]]
vault = "Personal"

# Swap Commerce account: kuba.swap (github-swap host alias)
[[ssh-keys]]
vault = "Employee"
